openapi: 3.1.0

info:
  title: Saher NGO Internal ERP API
  description: Internal ERP system for Saher NGO
  version: 1.0.0
  license:
    name: MIT

tags:
  - name: User
    description: User Management Operation
  - name: Admin
    description: Admin Management Operation
  - name: Auth
    description: Auth Management Operation
  - name: Bank
    description: Bank Management Operation
  - name: Upload
    description: Upload Management Operation
  - name: Account
    description: Account Management Operation

servers:
  - url: http://localhost:4000/api
    description: Local
  - url: https://api.saher.org/api
    description: Production

paths: 
  #Upload
  /upload/image:
    $ref: ./paths/upload/image-upload.yaml
  # --------------------------------------------------------------------- # 

  # Auth
  /auth/login:
    $ref: ./paths/auth/login.yaml
  /auth/logout:
    $ref: ./paths/auth/logout.yaml
  /auth/revalidate-token:
    $ref: ./paths/auth/revalidate-token.yaml
  /auth/me:
    $ref: ./paths/auth/me.yaml

  # --------------------------------------------------------------------- # 

  # Admin
  # Bank Operation
  /admin/bank/register:
    $ref: ./paths/admin/bank/register.yaml
  /admin/bank/get/{id}:
    $ref: ./paths/admin/bank/get.yaml
  /admin/bank/update/{id}:
    $ref: ./paths/admin/bank/update.yaml
  /admin/bank/delete/{id}:
    $ref: ./paths/admin/bank/delete.yaml

  # Account Operation
  /admin/account/register:
    $ref: ./paths/admin/account/register.yaml
  /admin/account/get/{id}:
    $ref: ./paths/admin/account/get.yaml
  /admin/account/update/{id}:
    $ref: ./paths/admin/account/update.yaml
  /admin/account/delete/{id}:
    $ref: ./paths/admin/account/delete.yaml

  # User Operation
  /user/get/{id}:
    $ref: ./paths/user/get.yaml
  /user/update/{id}:
    $ref: ./paths/user/update.yaml
  /user/delete/{id}:
    $ref: ./paths/user/delete.yaml

  # --------------------------------------------------------------------- # 

  # Attendance
    # Mark
  /attendance/check-in:
    $ref: ./paths/attendance/check-in.yaml
  /attendance/check-out:
    $ref: ./paths/attendance/check-out.yaml
  /attendance/correction:
    $ref: ./paths/attendance/correction/create.yaml
  /attendance/correction/{id}:
    $ref: ./paths/attendance/correction/update.yaml

    # Holiday
  /attendance/holiday/create:
    $ref: ./paths/attendance/holiday/create.yaml
  /attendance/holiday/update/{id}:
    $ref: ./paths/attendance/holiday/update.yaml
  /attendance/holiday/get-all:
    $ref: ./paths/attendance/holiday/get-all.yaml
  /attendance/holiday/get/{id}:
    $ref: ./paths/attendance/holiday/get.yaml
  /attendance/holiday/delete/{id}:
    $ref: ./paths/attendance/holiday/delete.yaml

    # Export Report

components:
  securitySchemes:
    accessCookie:
      type: apiKey
      in: cookie
      name: saher_access_token
    refreshCookie:
      type: apiKey
      in: cookie
      name: saher_refresh_token

security:
  - accessCookie: []
