openapi: 3.1.0

info:
  title: Saher NGO Internal ERP API
  description: Internal ERP system for Saher NGO
  version: 1.0.0
  license:
    name: MIT

servers:
  - url: http://localhost:4000/api
    description: Local

paths:
  $ref: "./paths.yaml"

components:
  $ref: "./components.yaml"
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: access_token

security:
  - cookieAuth: []

