openapi: 3.1.0

info:
  title: Saher NGO Internal ERP API
  description: Internal ERP system for Saher NGO
  version: 1.0.0
  license:
    name: MIT

tags:
  - name: User
    description: User Management Operation
  - name: Admin
    description: Admin Management Operation
  - name: Auth
    description: Auth Management Operation
  - name: Bank
    description: Bank Management Operation
  - name: Upload
    description: Upload Management Operation

servers:
  - url: http://localhost:4000/api
    description: Local
  - url: https://api.saher.org/api
    description: Production

paths: 
  #Upload
  /upload/image:
    $ref: ./paths/upload/image-upload.yaml

  # Auth
  /auth/login:
    $ref: ./paths/auth/login.yaml
  /auth/logout:
    $ref: ./paths/auth/logout.yaml
  /auth/revalidate-token:
    $ref: ./paths/auth/revalidate-token.yaml
  /auth/me:
    $ref: ./paths/auth/me.yaml

  # Admin
  # Bank Operation
  /admin/bank/register:
    $ref: ./paths/admin/bank/register.yaml
  /admin/bank/get/{id}:
    $ref: ./paths/admin/bank/get.yaml
  /admin/bank/update/{id}:
    $ref: ./paths/admin/bank/update.yaml
  /admin/bank/delete/{id}:
    $ref: ./paths/admin/bank/delete.yaml

components:
  securitySchemes:
    accessCookie:
      type: apiKey
      in: cookie
      name: saher_access_token
    refreshCookie:
      type: apiKey
      in: cookie
      name: saher_refresh_token

security:
  - accessCookie: []
