openapi: 3.1.0

info:
  title: Saher NGO Internal ERP API
  description: Internal ERP system for Saher NGO
  version: 1.0.0
  license:
    name: MIT

tags:
  - name: User
    description: User Management Operation
  - name: Admin
    description: Admin Management Operation
  - name: Auth
    description: Auth Management Operation

servers:
  - url: http://localhost:4000/api
    description: Local
  - url: https://api.saher.org/api
    description: Production

paths: 
  # Auth
  /auth/login:
    $ref: ./paths/auth/login.yaml


components:
  securitySchemes:
    accessCookie:
      type: apiKey
      in: cookie
      name: saher_access_token
    refreshCookie:
      type: apiKey
      in: cookie
      name: saher_refresh_token

security:
  - accessCookie: []
